[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
milkerfun = "3Jt5qxxkHpsCq5m8XLu1L6QFKFwyU3t2xbiM7x4YTPxm"

[programs.mainnet]
milkerfun = "3Jt5qxxkHpsCq5m8XLu1L6QFKFwyU3t2xbiM7x4YTPxm"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
